require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'config/**/**'
    - 'bin/**/**'
    - 'lib/**/**'
    - 'vendor/**/**'

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false