name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUBY_VERSION: 3.1.2

jobs:
  lint:
    name: Lint and audit code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Prepare ENV
        run: |
          sudo apt-get update
          sudo apt-get install libvips42=8.9.1-2
      - name: Run Bundler check and audit
        run: bundle exec bundle-audit check --update

      - name: Run rubocop
        run: bundle exec rubocop

  test:
    needs: lint
    name: Test with RSpec
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:14.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Prepare ENV
        run: |
          sudo apt-get update
          bundle exec rake assets:precompile
          bundle exec bin/rails db:test:prepare

      - name: Run RSpec
        run: bundle exec rspec spec
